//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.Test
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Квартира.
    /// </summary>
    // *** Start programmer edit section *** (Квартира CustomAttributes)

    // *** End programmer edit section *** (Квартира CustomAttributes)
    [AutoAltered()]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("КвартираE", new string[] {
            "Номер as \'Номер\'",
            "Кв as \'Кв\'",
            "Здание as \'Здание\'",
            "Здание.Наимен as \'Наимен\'"}, Hidden=new string[] {
            "Здание.Наимен"})]
    [MasterViewDefineAttribute("КвартираE", "Здание", ICSSoft.STORMNET.LookupTypeEnum.Standard, "", "Наимен")]
    [View("КвартираL", new string[] {
            "Номер as \'Номер\'",
            "Кв as \'Кв\'",
            "Здание.Наимен as \'Наимен\'"})]
    public class Квартира : ICSSoft.STORMNET.DataObject
    {
        
        private int fНомер;
        
        private IIS.Test.Квартиры fКв;
        
        private IIS.Test.Здание fЗдание;
        
        // *** Start programmer edit section *** (Квартира CustomMembers)

        // *** End programmer edit section *** (Квартира CustomMembers)

        
        /// <summary>
        /// Кв.
        /// </summary>
        // *** Start programmer edit section *** (Квартира.Кв CustomAttributes)

        // *** End programmer edit section *** (Квартира.Кв CustomAttributes)
        public virtual IIS.Test.Квартиры Кв
        {
            get
            {
                // *** Start programmer edit section *** (Квартира.Кв Get start)

                // *** End programmer edit section *** (Квартира.Кв Get start)
                IIS.Test.Квартиры result = this.fКв;
                // *** Start programmer edit section *** (Квартира.Кв Get end)

                // *** End programmer edit section *** (Квартира.Кв Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Квартира.Кв Set start)

                // *** End programmer edit section *** (Квартира.Кв Set start)
                this.fКв = value;
                // *** Start programmer edit section *** (Квартира.Кв Set end)

                // *** End programmer edit section *** (Квартира.Кв Set end)
            }
        }
        
        /// <summary>
        /// Номер.
        /// </summary>
        // *** Start programmer edit section *** (Квартира.Номер CustomAttributes)

        // *** End programmer edit section *** (Квартира.Номер CustomAttributes)
        public virtual int Номер
        {
            get
            {
                // *** Start programmer edit section *** (Квартира.Номер Get start)

                // *** End programmer edit section *** (Квартира.Номер Get start)
                int result = this.fНомер;
                // *** Start programmer edit section *** (Квартира.Номер Get end)

                // *** End programmer edit section *** (Квартира.Номер Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Квартира.Номер Set start)

                // *** End programmer edit section *** (Квартира.Номер Set start)
                this.fНомер = value;
                // *** Start programmer edit section *** (Квартира.Номер Set end)

                // *** End programmer edit section *** (Квартира.Номер Set end)
            }
        }
        
        /// <summary>
        /// Квартира.
        /// </summary>
        // *** Start programmer edit section *** (Квартира.Здание CustomAttributes)

        // *** End programmer edit section *** (Квартира.Здание CustomAttributes)
        [PropertyStorage(new string[] {
                "Здание"})]
        [NotNull()]
        public virtual IIS.Test.Здание Здание
        {
            get
            {
                // *** Start programmer edit section *** (Квартира.Здание Get start)

                // *** End programmer edit section *** (Квартира.Здание Get start)
                IIS.Test.Здание result = this.fЗдание;
                // *** Start programmer edit section *** (Квартира.Здание Get end)

                // *** End programmer edit section *** (Квартира.Здание Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Квартира.Здание Set start)

                // *** End programmer edit section *** (Квартира.Здание Set start)
                this.fЗдание = value;
                // *** Start programmer edit section *** (Квартира.Здание Set end)

                // *** End programmer edit section *** (Квартира.Здание Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "КвартираE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View КвартираE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("КвартираE", typeof(IIS.Test.Квартира));
                }
            }
            
            /// <summary>
            /// "КвартираL" view.
            /// </summary>
            public static ICSSoft.STORMNET.View КвартираL
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("КвартираL", typeof(IIS.Test.Квартира));
                }
            }
        }
    }
}
