//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.Test
{
    using System;
    using System.Xml;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Квартиры.
    /// </summary>
    // *** Start programmer edit section *** (Квартиры CustomAttributes)

    // *** End programmer edit section *** (Квартиры CustomAttributes)
    public enum Квартиры
    {
        
        // *** Start programmer edit section *** (Квартиры.1 CustomAttributes)

        // *** End programmer edit section *** (Квартиры.1 CustomAttributes)
        1,
        
        // *** Start programmer edit section *** (Квартиры.2 CustomAttributes)

        // *** End programmer edit section *** (Квартиры.2 CustomAttributes)
        2,
        
        // *** Start programmer edit section *** (Квартиры.3 CustomAttributes)

        // *** End programmer edit section *** (Квартиры.3 CustomAttributes)
        3,
    }
}
